global:
  scrape_interval: 15s # Fréquence de récupération des données

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter' # Simulation de surveillance serveur
    static_configs:
      - targets: ['node-exporter:9100']
